services:
  db:
    image: mysql
    container_name: uuboydb
    restart: always
    environment:
      MYSQL_DATABASE: 'testdb'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'uuboyscy'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'howdoyouturnthison'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3307:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
